export const SETTING_ASF_SERVER = "SETTING_ASF_SERVER";
export const SETTING_ASF_PORT = "SETTING_ASF_PORT";
export const SETTING_ASF_PASSWORD = "SETTING_ASF_PASSWORD";
export const SETTING_INSPECT_ITEMS = "SETTING_INSPECT_ITEMS";
export const SETTING_INSPECT_CACHE_TIME_HOURS = "SETTING_INSPECT_CACHE_TIME_HOURS";
export const SETTING_INTERFACE_AUTOSTOP_MINUTES = "SETTING_INTERFACE_AUTOSTOP_MINUTES";

export const DEFAULT_SETTINGS = {
	SETTING_ASF_SERVER: "http://localhost",
	SETTING_ASF_PORT: "1242",
	SETTING_ASF_PASSWORD: "",
	SETTING_INSPECT_ITEMS: true,
	SETTING_INSPECT_CACHE_TIME_HOURS: -1,
	SETTING_INTERFACE_AUTOSTOP_MINUTES: 15,
};

export function GetSetting(name) {
	return GM_getValue(name, DEFAULT_SETTINGS[name]);
}

export function SetSetting(name, value) {
	GM_setValue(name, value);
}
